language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anindakar0104/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anindakar0104/docker-react npm run test
  ## -e CI=true --> for running tests in travis-ci